import { Command } from 'commander'
import { resolve, dirname } from 'node:path'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { loadConfig } from '../config-loader'
import { scanReactRouterFiles } from '../scanners/react-router'
import { scanNextJsAppDir } from '../scanners/nextjs-app'
import { scanNextJsPagesDir } from '../scanners/nextjs-pages'
import { generateSitemap } from '../generators/sitemap'
import type { CmdkEngineConfig, SitemapRoute } from '../../core/types'

export const scanCommand = new Command('scan')
  .description('Scan project routes and generate a command sitemap')
  .option('-c, --config <path>', 'Path to config file', 'cmdk-engine.config.ts')
  .option('-o, --output <path>', 'Output file path (overrides config)')
  .option('-f, --format <format>', 'Output format: json or ts', 'json')
  .option('--framework <framework>', 'Framework: react-router, nextjs-app, nextjs-pages')
  .option('--routes-dir <dir>', 'Directory to scan for routes')
  .action(async (options) => {
    try {
      const config = await loadConfig(options.config)
      const framework = options.framework ?? config.framework ?? detectFramework()
      const routesDir = options.routesDir ?? config.routesDir ?? detectRoutesDir(framework)
      const outputPath = options.output ?? config.output ?? 'src/generated/command-routes.json'

      console.log(`Scanning ${framework} routes in ${routesDir}...`)

      let routes: SitemapRoute[] = []

      switch (framework) {
        case 'react-router':
          routes = scanReactRouterFiles(resolve(routesDir))
          break
        case 'nextjs-app':
          routes = scanNextJsAppDir(resolve(routesDir))
          break
        case 'nextjs-pages':
          routes = scanNextJsPagesDir(resolve(routesDir))
          break
        default:
          console.error(`Unknown framework: ${framework}`)
          process.exit(1)
      }

      // Apply overrides from config
      if (config.overrides) {
        routes = applyOverrides(routes, config.overrides)
      }

      // Apply exclusions
      if (config.exclude) {
        routes = applyExclusions(routes, config.exclude)
      }

      const sitemap = generateSitemap(routes, framework)

      // Ensure output directory exists
      const outputDir = dirname(resolve(outputPath))
      if (!existsSync(outputDir)) {
        mkdirSync(outputDir, { recursive: true })
      }

      if (options.format === 'ts') {
        const tsOutput = `// Auto-generated by cmdk-engine scan\n// Do not edit manually\n\nimport type { Sitemap } from 'cmdk-engine'\n\nexport const commandRoutes: Sitemap = ${JSON.stringify(sitemap, null, 2)} as const\n`
        writeFileSync(resolve(outputPath.replace(/\.json$/, '.ts')), tsOutput, 'utf-8')
      } else {
        writeFileSync(resolve(outputPath), JSON.stringify(sitemap, null, 2), 'utf-8')
      }

      console.log(`Found ${routes.length} routes`)
      console.log(`Written to ${outputPath}`)
    } catch (error) {
      console.error('Scan failed:', (error as Error).message)
      process.exit(1)
    }
  })

function detectFramework(): string {
  if (existsSync('next.config.ts') || existsSync('next.config.js') || existsSync('next.config.mjs')) {
    // Check if using app router
    if (existsSync('app') || existsSync('src/app')) {
      return 'nextjs-app'
    }
    return 'nextjs-pages'
  }

  // Check for React Router by looking for route files
  if (existsSync('src/routes') || existsSync('src/router.tsx') || existsSync('src/router.ts')) {
    return 'react-router'
  }

  return 'react-router' // default
}

function detectRoutesDir(framework: string): string {
  switch (framework) {
    case 'nextjs-app':
      return existsSync('src/app') ? 'src/app' : 'app'
    case 'nextjs-pages':
      return existsSync('src/pages') ? 'src/pages' : 'pages'
    case 'react-router':
      return existsSync('src/routes') ? 'src/routes' : 'src'
    default:
      return 'src'
  }
}

function applyOverrides(
  routes: SitemapRoute[],
  overrides: NonNullable<CmdkEngineConfig['overrides']>,
): SitemapRoute[] {
  return routes.map((route) => {
    const override = overrides[route.path]
    if (!override) return route

    return {
      ...route,
      label: override.label ?? route.label,
      keywords: override.keywords
        ? [...new Set([...route.keywords, ...override.keywords])]
        : route.keywords,
      group: override.group ?? route.group,
    }
  })
}

function applyExclusions(routes: SitemapRoute[], exclude: string[]): SitemapRoute[] {
  return routes.filter((route) => {
    return !exclude.some((pattern) => {
      if (pattern.endsWith('*')) {
        return route.path.startsWith(pattern.slice(0, -1))
      }
      return route.path === pattern
    })
  })
}
